# Generated by Django 6.0.6 on 2026-06-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ca', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=150)),
                ('validade_ca', models.DateField()),
                ('vida_util_dias', models.PositiveIntegerField()),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
                ('quantidade_estoque', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
