# Generated by Django 6.0.6 on 2026-06-05 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste')], max_length=20)),
                ('quantidade', models.PositiveIntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.epi')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
