# Generated by Django 6.0.6 on 2026-06-04 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('motivo', models.CharField(choices=[('primeira', 'Primeira Entrega'), ('troca', 'Troca por Desgaste'), ('perda', 'Perda'), ('danificado', 'Danificado')], max_length=20)),
                ('data_entrega', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.epi')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
        ),
    ]
