# Generated by Django 6.0.6 on 2026-06-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='data_proxima_troca',
            field=models.DateField(blank=True, null=True),
        ),
    ]
