# Generated by Django 6.0.6 on 2026-06-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0002_entregaepi_data_proxima_troca'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='assinatura',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/'),
        ),
    ]
