# Generated by Django 6.0.6 on 2026-06-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0003_entregaepi_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='data_confirmacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='token_confirmacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
