# Generated by Django 6.0.6 on 2026-06-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0004_entregaepi_confirmado_entregaepi_data_confirmacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='biometria_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='metodo_confirmacao',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
