# Generated by Django 6.0.6 on 2026-06-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0005_entregaepi_biometria_confirmada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaepi',
            name='metodo_confirmacao',
            field=models.CharField(blank=True, choices=[('assinatura', 'Assinatura'), ('qr_code', 'QR Code'), ('biometria', 'Biometria')], max_length=20, null=True),
        ),
    ]
