# Generated by Django 6.0.6 on 2026-06-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0006_alter_entregaepi_metodo_confirmacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='ip_confirmacao',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='user_agent_confirmacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
