# Generated by Django 6.0.6 on 2026-06-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0007_entregaepi_ip_confirmacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
