# Generated by Django 6.0.6 on 2026-06-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credencialbiometrica',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='credencialbiometrica',
            name='credential_id',
            field=models.TextField(unique=True),
        ),
    ]
