# Generated by Django 6.0.6 on 2026-06-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometria', '0002_credencialbiometrica_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credencialbiometrica',
            name='sign_count',
            field=models.IntegerField(default=0),
        ),
    ]
