# Generated by Django 6.0.6 on 2026-07-23 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometria', '0003_credencialbiometrica_sign_count'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credencialbiometrica',
            old_name='public_key',
            new_name='template_base64',
        ),
        migrations.RemoveField(
            model_name='credencialbiometrica',
            name='credential_id',
        ),
        migrations.RemoveField(
            model_name='credencialbiometrica',
            name='sign_count',
        ),
        migrations.AddField(
            model_name='credencialbiometrica',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='credencialbiometrica',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credencial_biometrica', to='funcionarios.funcionario'),
        ),
    ]
