# Generated by Django 6.0.6 on 2026-07-24 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometria', '0004_rename_public_key_credencialbiometrica_template_base64_and_more'),
        ('entregas', '0008_entregaepi_ativo'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoValidacaoBiometrica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('expirada', 'Expirada'), ('utilizada', 'Utilizada')], default='pendente', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('ip_solicitante', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('mensagem', models.CharField(blank=True, max_length=255)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_biometricas', to='entregas.entregaepi')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_biometricas', to='funcionarios.funcionario')),
            ],
        ),
    ]
